#include <string.h>

void doText(char* banner)
{
    banner[0] = 0;
    strcat(banner, "                                    ");
    strcat(banner, "Welcome to SLIME! This little program is intended for use ");
    strcat(banner, "as a watery/slimey substance simulator. It was programmed ");
    strcat(banner, "in a few days while bored at CTI. If you want to contact ");
    strcat(banner, "me about it, and ask for updates or whatever, please drop ");
    strcat(banner, "me an e-mail at tamburlaine@webmail.co.za and I will reply ");
    strcat(banner, "asap. Greetz: WiReZ, antiv0id, DiGiTaL-FiRe, websk8r, ");
    strcat(banner, "vythos and iceburg.  Yes, this app was coded in 2002. And ");
    strcat(banner, "for all you lamers who say DOS is crap...   Too hell with ");
    strcat(banner, "you all! DOS rules! :p    For those people who dont know ");
    strcat(banner, "how to use this program, here is a quick guide.   You will ");
    strcat(banner, "see there is a panel on the right with buttons on it.  The ");
    strcat(banner, "button at the top is the rain button. Clicking it turns the ");
    strcat(banner, "rain on or off. The next three buttons are your right-click ");
    strcat(banner, "buttons. Use these to decide what you want the simulator to ");
    strcat(banner, "do when you right-click the mouse button. The next two buttons ");
    strcat(banner, "affect what happens when you left-click the mouse button. ");
    strcat(banner, "So, the button under the rain button (button number 2) adds ");
    strcat(banner, "water when you right-click. This is apparent by the plus in the ");
    strcat(banner, "blue background, which symbolised adding water. Button 3, the ");
    strcat(banner, "button with the minus symbol and a line means removing lines. ");
    strcat(banner, "You can use this to remove any lines you dont want. Button 4 ");
    strcat(banner, "is the button you will use to remove some water in a small ");
    strcat(banner, "area. It's useful for clearing up where the water has messed ");
    strcat(banner, "or spilled. The button under that, button number 5, is the button ");
    strcat(banner, "that you will use to add straight lines to the scene. The button ");
    strcat(banner, "underneath that one is the add freeform line. Use this to ");
    strcat(banner, "'scribble' lines all over the place. There are two smaller buttons under that. ");
    strcat(banner, "The white one is used when you want to erase all lines, but keep the water. ");
    strcat(banner, "The blue one is used when you want to erase all water without losing any lines. ");
    strcat(banner, "The larger button underneath (with an N on it) can be used to clear both lines ");
    strcat(banner, "and water at the same time. It will also stop the rain if it was on. ");
    strcat(banner, "You can use 'p' to pause if you dont want to click the button. ");
    strcat(banner, " ");
    strcat(banner, " ");
    strcat(banner, "To quit the simulation, hit space. Thats it for now. Enjoy yourself. ");
    strcat(banner, " ");
    strcat(banner, "                                            ");
}